"use client";
import React from "react";
import { motion } from "framer-motion";

type Props = {};

const Cms = (props: Props) => {
  return (
    <svg
      id="files"
      className="fill-white dark:fill-[#2b2b2b]"
      x="0px"
      y="0px"
      viewBox="0 0 500 328.7"
      xmlns="http://www.w3.org/2000/svg"
    >
      {/* <style>
  rect{
    fill: var(--st-bg-color);
  }
  @keyframes document1-motion {
      0% {
          transform:  translate(0em,50em);
      }
      20% {
          transform:  translate(-5em,-2em);
      }
      40% {
          transform:  translate(-2em,0em);
      }
      60% {
          transform:  translate(-7em,-2em);
      }
      100% {
          transform:  translate(0em,0em);
      }
  }
  @keyframes document2-motion {
      0% {
          transform:  translate(0em,50em);
      }
      20% {
          transform:  translate(5em,2em);
      }
      40% {
          transform:  translate(2em,0em);
      }
      60% {
          transform:  translate(7em,2em);
      }
      100% {
          transform:  translate(1em,1em);
      }
  }
  @keyframes document3-motion {
      0% {
          transform:  translate(-50em,0em);
      }
      20% {
          transform:  translate(1em,3em);
      }
      40% {
          transform:  translate(-7em,-3em);
      }
      60% {
          transform:  translate(5em,2em);
      }
      100% {
          transform:  translate(2em,2em);
      }
  }
  .document {
      transform                  : translate(0em,50em);
      transition-timing-function : ease-in-out;
  }
  :host(.file_show) #document1{
      animation-name      : document1-motion;
      animation-duration  : 3s;
      animation-delay     : 0.5s;
      animation-fill-mode : forwards;
  }
  :host(.file_show) #document2{
      animation-name      : document2-motion;
      animation-duration  : 3s;
      animation-delay     : 0.5s;
      animation-fill-mode : forwards;
  }
  :host(.file_show) #document3{
      animation-name      : document3-motion;
      animation-duration  : 3s;
      animation-delay     : 0.5s;
      animation-fill-mode : forwards;
  }
  </style> */}
      <motion.g
        animate={{
          x: [800, 16, 112, 80, 32],
          y: [0, 48, -48, 32, 32],
          transition: {
            duration: 3,
            ease: "easeInOut",
          },
        }}
        className="document"
        id="document3"
      >
        <rect
          x="197.3"
          y="92.4"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="130.4"
          height="165.4"
        ></rect>
        <rect
          x="211.3"
          y="170"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="32.6"
          height="64.1"
        ></rect>
        <motion.g>
          <line fill="none" x1="258.5" y1="234" x2="313.6" y2="234"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="234"
              x2="260.5"
              y2="234"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="264.4"
              y1="234"
              x2="309.7"
              y2="234"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="311.6"
              y1="234"
              x2="313.6"
              y2="234"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="258.5" y1="217.7" x2="313.6" y2="217.7"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="217.7"
              x2="260.5"
              y2="217.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="264.4"
              y1="217.7"
              x2="309.7"
              y2="217.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="311.6"
              y1="217.7"
              x2="313.6"
              y2="217.7"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="258.5" y1="201.4" x2="313.6" y2="201.4"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="201.4"
              x2="260.5"
              y2="201.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="264.4"
              y1="201.4"
              x2="309.7"
              y2="201.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="311.6"
              y1="201.4"
              x2="313.6"
              y2="201.4"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="258.5" y1="186.2" x2="313.6" y2="186.2"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="186.2"
              x2="260.5"
              y2="186.2"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="264.4"
              y1="186.2"
              x2="309.7"
              y2="186.2"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="311.6"
              y1="186.2"
              x2="313.6"
              y2="186.2"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="258.5" y1="170" x2="313.6" y2="170"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="170"
              x2="260.5"
              y2="170"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="264.4"
              y1="170"
              x2="309.7"
              y2="170"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="311.6"
              y1="170"
              x2="313.6"
              y2="170"
            ></line>
          </motion.g>
        </motion.g>

        <rect
          x="281.4"
          y="107.4"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="32.6"
          height="32.6"
        ></rect>
        <motion.g>
          <line fill="none" x1="211.1" y1="140" x2="266.2" y2="140"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="211.1"
              y1="140"
              x2="213.1"
              y2="140"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="217"
              y1="140"
              x2="262.3"
              y2="140"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="264.2"
              y1="140"
              x2="266.2"
              y2="140"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="211.1" y1="123.7" x2="266.2" y2="123.7"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="211.1"
              y1="123.7"
              x2="213.1"
              y2="123.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="217"
              y1="123.7"
              x2="262.3"
              y2="123.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="264.2"
              y1="123.7"
              x2="266.2"
              y2="123.7"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="211.1" y1="107.4" x2="266.2" y2="107.4"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="211.1"
              y1="107.4"
              x2="213.1"
              y2="107.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="217"
              y1="107.4"
              x2="262.3"
              y2="107.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="264.2"
              y1="107.4"
              x2="266.2"
              y2="107.4"
            ></line>
          </motion.g>
        </motion.g>
      </motion.g>
      <motion.g
        animate={{
          x: [0, 80, 32, 112, 16],
          y: [800, 32, 0, 32, 16],
          transition: {
            duration: 3,
            ease: "easeInOut",
          },
        }}
        className="document"
        id="document2"
      >
        <rect
          x="191.8"
          y="92.4"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="130.4"
          height="165.4"
        ></rect>
        <rect
          x="275.8"
          y="107.3"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="32.6"
          height="32.6"
        ></rect>
        <motion.g>
          <line fill="none" x1="205.4" y1="139.9" x2="260.5" y2="139.9"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="205.4"
              y1="139.9"
              x2="207.4"
              y2="139.9"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="211.3"
              y1="139.9"
              x2="256.6"
              y2="139.9"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="139.9"
              x2="260.5"
              y2="139.9"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="205.4" y1="123.6" x2="260.5" y2="123.6"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="205.4"
              y1="123.6"
              x2="207.4"
              y2="123.6"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="211.3"
              y1="123.6"
              x2="256.6"
              y2="123.6"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="123.6"
              x2="260.5"
              y2="123.6"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="205.4" y1="107.3" x2="260.5" y2="107.3"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="205.4"
              y1="107.3"
              x2="207.4"
              y2="107.3"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="211.3"
              y1="107.3"
              x2="256.6"
              y2="107.3"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="258.5"
              y1="107.3"
              x2="260.5"
              y2="107.3"
            ></line>
          </motion.g>
        </motion.g>

        <rect
          x="205.8"
          y="201.4"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="32.6"
          height="32.6"
        ></rect>
        <motion.g>
          <line fill="none" x1="253" y1="234" x2="308.1" y2="234"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="253"
              y1="234"
              x2="255"
              y2="234"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="258.9"
              y1="234"
              x2="304.2"
              y2="234"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="306.1"
              y1="234"
              x2="308.1"
              y2="234"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="253" y1="217.7" x2="308.1" y2="217.7"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="253"
              y1="217.7"
              x2="255"
              y2="217.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="258.9"
              y1="217.7"
              x2="304.2"
              y2="217.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="306.1"
              y1="217.7"
              x2="308.1"
              y2="217.7"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="253" y1="201.4" x2="308.1" y2="201.4"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="253"
              y1="201.4"
              x2="255"
              y2="201.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="258.9"
              y1="201.4"
              x2="304.2"
              y2="201.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="306.1"
              y1="201.4"
              x2="308.1"
              y2="201.4"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="308.1" y1="155.4" x2="205.2" y2="155.4"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="308.1"
              y1="155.4"
              x2="306.1"
              y2="155.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9566,3.9566"
              x1="302.2"
              y1="155.4"
              x2="209.2"
              y2="155.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="207.2"
              y1="155.4"
              x2="205.2"
              y2="155.4"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="308.1" y1="170.8" x2="205.2" y2="170.8"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="308.1"
              y1="170.8"
              x2="306.1"
              y2="170.8"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9566,3.9566"
              x1="302.2"
              y1="170.8"
              x2="209.2"
              y2="170.8"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="207.2"
              y1="170.8"
              x2="205.2"
              y2="170.8"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="308.1" y1="186.2" x2="205.2" y2="186.2"></line>
        </motion.g>
      </motion.g>
      <motion.g
        animate={{
          x: [0, -80, -32, -112, 0],
          y: [800, -32, 0, -32, 0],
          transition: {
            duration: 3,
            ease: "easeInOut",
          },
        }}
        className="document"
        id="document1"
      >
        <rect
          x="185.8"
          y="92.4"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="130.4"
          height="165.4"
        ></rect>
        <rect
          x="199.5"
          y="107.3"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="102.9"
          height="32.8"
        ></rect>
        <rect
          x="199.4"
          y="201.4"
          stroke="#3FAE29"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          width="32.6"
          height="32.6"
        ></rect>
        <motion.g>
          <line fill="none" x1="302.4" y1="155.4" x2="199.5" y2="155.4"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="302.4"
              y1="155.4"
              x2="300.4"
              y2="155.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9566,3.9566"
              x1="296.5"
              y1="155.4"
              x2="203.5"
              y2="155.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="201.5"
              y1="155.4"
              x2="199.5"
              y2="155.4"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="302.4" y1="170.8" x2="199.5" y2="170.8"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="302.4"
              y1="170.8"
              x2="300.4"
              y2="170.8"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9566,3.9566"
              x1="296.5"
              y1="170.8"
              x2="203.5"
              y2="170.8"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="201.5"
              y1="170.8"
              x2="199.5"
              y2="170.8"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="302.4" y1="186.3" x2="199.5" y2="186.3"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="302.4"
              y1="186.3"
              x2="300.4"
              y2="186.3"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9566,3.9566"
              x1="296.5"
              y1="186.3"
              x2="203.5"
              y2="186.3"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="201.5"
              y1="186.3"
              x2="199.5"
              y2="186.3"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="302.4" y1="201.4" x2="247.3" y2="201.4"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="302.4"
              y1="201.4"
              x2="300.4"
              y2="201.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="296.5"
              y1="201.4"
              x2="251.2"
              y2="201.4"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="249.3"
              y1="201.4"
              x2="247.3"
              y2="201.4"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="302.4" y1="217.7" x2="247.3" y2="217.7"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="302.4"
              y1="217.7"
              x2="300.4"
              y2="217.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="296.5"
              y1="217.7"
              x2="251.2"
              y2="217.7"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="249.3"
              y1="217.7"
              x2="247.3"
              y2="217.7"
            ></line>
          </motion.g>
        </motion.g>
        <motion.g>
          <line fill="none" x1="302.4" y1="234" x2="247.3" y2="234"></line>
          <motion.g>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="302.4"
              y1="234"
              x2="300.4"
              y2="234"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeDasharray="3.9347,3.9347"
              x1="296.5"
              y1="234"
              x2="251.2"
              y2="234"
            ></line>
            <line
              fill="none"
              stroke="#3FAE29"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              x1="249.3"
              y1="234"
              x2="247.3"
              y2="234"
            ></line>
          </motion.g>
        </motion.g>
      </motion.g>
    </svg>
  );
};

export default Cms;
